{{- if and (eq .Values.storage.driver "sqlite") .Values.storage.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "audit.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "audit.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size }}
  {{- with .Values.storage.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
